
### save a blog. 
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "My third saved blog",
    "author": "Jane Doe",
    "url": "BlogsFromJaneDoe.org/43527845278",
    "likes": 15
}

### get all saved blogs. 
GET http://localhost:3003/api/blogs

### Delete a saved blog by id 
DELETE http://localhost:3003/api/blogs/6374d75e8effcb82cfb53d7c

### update a saved blog 
PUT http://localhost:3003/api/blogs/6374dfe577eb499226effdb9
content-type: application/json

{
    "author": "another title"
}

### create a new user - (and testing duplicate username)
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "7Cedars",
    "name": "Cedars Seven",
    "password": "Te33333"
}

### get all users - (and testing duplicate username)
GET http://localhost:3003/api/users

